
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAccessor;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class libSystemGUI extends javax.swing.JFrame {

  
    public libSystemGUI() {
        initComponents();
        loadLibrary();
        showLibList();
        loadLibBorrowed();
        loadLibAvail();
        loadAllBooks();
    }
    
           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLocation = new javax.swing.JLabel();
        jTabbedPaneLib = new javax.swing.JTabbedPane();
        jPannelAddLib = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLibList = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLibBooks = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTLibID = new javax.swing.JTextField();
        jTLibName = new javax.swing.JTextField();
        jTLibAddress = new javax.swing.JTextField();
        jButtonAddLib = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonUpdateLib = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jPanelBooks = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableBookList = new javax.swing.JTable();
        jTISBN = new javax.swing.JTextField();
        jTbookTitle = new javax.swing.JTextField();
        jTBookAuthor = new javax.swing.JTextField();
        jTPrice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxLocation = new javax.swing.JComboBox<>();
        jButtonAddBook = new javax.swing.JButton();
        jBclear = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelUpdateISBN = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTUpdateBookTitle = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTUpdateBookAuthor = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTUpdatePrice = new javax.swing.JTextField();
        jButtonUpdateBook = new javax.swing.JButton();
        jComboBoxUpdateBook = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBorrowed = new javax.swing.JTable();
        jComboBoxBorrowed = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldBorrower = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabelBookTitle = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelISBN = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableAvail = new javax.swing.JTable();
        jButtonBorrowBook = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabelBorrowDate = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabelR = new javax.swing.JLabel();
        jLabelReturnDate = new javax.swing.JLabel();
        jButtonReturnBook = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabelLibLoc = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library System 1.0");

        jPannelAddLib.setBackground(new java.awt.Color(153, 255, 255));

        jTableLibList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Library ID", "Library Name", "Library Location"
            }
        ));
        jTableLibList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLibListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLibList);

        jTableLibBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book Title", "ISBN", "Author", "Price"
            }
        ));
        jScrollPane2.setViewportView(jTableLibBooks);

        jLabel1.setText("Library Locations:");

        jLabel2.setText("Library Books");

        jLabel3.setText("Library ID:");

        jLabel4.setText("Library Name:");

        jLabel5.setText("Library Address:");

        jButtonAddLib.setText("Add Library");
        jButtonAddLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddLibActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonUpdateLib.setText("Update Library");
        jButtonUpdateLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateLibActionPerformed(evt);
            }
        });

        jButton2.setText("Delete Library");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel27.setText("Note: Highlight the item to delete or update.");

        javax.swing.GroupLayout jPannelAddLibLayout = new javax.swing.GroupLayout(jPannelAddLib);
        jPannelAddLib.setLayout(jPannelAddLibLayout);
        jPannelAddLibLayout.setHorizontalGroup(
            jPannelAddLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPannelAddLibLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUpdateLib)
                .addGap(25, 25, 25))
            .addGroup(jPannelAddLibLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPannelAddLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPannelAddLibLayout.createSequentialGroup()
                        .addGroup(jPannelAddLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPannelAddLibLayout.createSequentialGroup()
                                .addGroup(jPannelAddLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPannelAddLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPannelAddLibLayout.createSequentialGroup()
                                        .addComponent(jButtonClear)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonAddLib)
                                        .addGap(19, 19, 19))
                                    .addComponent(jTLibName, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                                    .addComponent(jTLibAddress)
                                    .addComponent(jTLibID)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPannelAddLibLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPannelAddLibLayout.setVerticalGroup(
            jPannelAddLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPannelAddLibLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPannelAddLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTLibID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPannelAddLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTLibName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPannelAddLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTLibAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPannelAddLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddLib)
                    .addComponent(jButtonClear))
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(3, 3, 3)
                .addGroup(jPannelAddLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonUpdateLib)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneLib.addTab("Manage Library", jPannelAddLib);
        jPannelAddLib.getAccessibleContext().setAccessibleName("");

        jPanelBooks.setBackground(new java.awt.Color(153, 255, 255));

        jLabel13.setText("ISBN:");

        jTableBookList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN", "Book Title", "Book Author", "Book Location"
            }
        ));
        jTableBookList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBookListMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableBookList);

        jLabel14.setText("Book Title:");

        jLabel15.setText("Book Author:");

        jLabel16.setText("Book Location:");

        jLabel17.setText("Book Price:");

        jComboBoxLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButtonAddBook.setText("Add Book");
        jButtonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBookActionPerformed(evt);
            }
        });

        jBclear.setText("Clear");
        jBclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclearActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Add Book to the Library");

        jLabel19.setText("Book List in all Libraries");

        jLabel21.setText("ISBN:");

        jLabelUpdateISBN.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setText("Book Title:");

        jLabel25.setText("Book Author:");

        jLabel26.setText("Book Location:");

        jLabel23.setText("Book Price:");

        jButtonUpdateBook.setText("Update Book");
        jButtonUpdateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateBookActionPerformed(evt);
            }
        });

        jComboBoxUpdateBook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelBooksLayout = new javax.swing.GroupLayout(jPanelBooks);
        jPanelBooks.setLayout(jPanelBooksLayout);
        jPanelBooksLayout.setHorizontalGroup(
            jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanelBooksLayout.createSequentialGroup()
                        .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxLocation, 0, 331, Short.MAX_VALUE)
                            .addComponent(jTBookAuthor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTbookTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTISBN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTPrice)))
                    .addGroup(jPanelBooksLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBclear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddBook))
                    .addGroup(jPanelBooksLayout.createSequentialGroup()
                        .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelBooksLayout.createSequentialGroup()
                                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUpdateISBN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTUpdateBookTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTUpdateBookAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxUpdateBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTUpdatePrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonUpdateBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(49, Short.MAX_VALUE))))
        );
        jPanelBooksLayout.setVerticalGroup(
            jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(12, 12, 12)
                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTbookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jComboBoxLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBclear)
                    .addComponent(jButtonAddBook))
                .addGap(27, 27, 27)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUpdateISBN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTUpdateBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jTUpdateBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jComboBoxUpdateBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTUpdatePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonUpdateBook)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPaneLib.addTab("Manage Books", jPanelBooks);

        jTableBorrowed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ISBN", "Book Title", "Author", "Borrower", "Return Date"
            }
        ));
        jTableBorrowed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBorrowedMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableBorrowed);

        jComboBoxBorrowed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxBorrowed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBorrowedActionPerformed(evt);
            }
        });

        jLabel6.setText("View Borrowed Books in a Library");

        jLabel7.setText("View Available Book in Library");

        jButton1.setText("Borrow Book");

        jLabel8.setText("Enter Borrower's Name:");

        jLabel9.setText("Book Title:");

        jLabel10.setText("ISBN:");

        jTableAvail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book Title", "Book Author", "ISBN", "Location"
            }
        ));
        jTableAvail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAvailMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTableAvail);

        jButtonBorrowBook.setText("Borrow Book");
        jButtonBorrowBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrowBookActionPerformed(evt);
            }
        });

        jLabel20.setText("Library Location");

        jLabel22.setText("Borrow Date:");

        jLabelR.setText("Return Date:");

        jButtonReturnBook.setText("Return Book");
        jButtonReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnBookActionPerformed(evt);
            }
        });

        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldBorrower, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                                    .addComponent(jButtonBorrowBook, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelISBN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelBookTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabelR)
                                    .addComponent(jLabel20))
                                .addGap(120, 120, 120)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabelReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelBorrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelLibLoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxBorrowed, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxBorrowed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonReturnBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldBorrower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelBookTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabelISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelLibLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabelBorrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelR)
                                .addGap(456, 456, 456)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBorrowBook)))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap())))
        );

        jTabbedPaneLib.addTab("Borrow Books", jPanel1);

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneLib, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneLib, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxBorrowedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBorrowedActionPerformed
        loadLibBorrowed();
        loadLibAvail();
    }//GEN-LAST:event_jComboBoxBorrowedActionPerformed

    private void jButtonAddLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddLibActionPerformed
        // TODO add your handling code here:
       int id = Integer.parseInt(jTLibID.getText());
       String name = jTLibName.getText();
       String loc = jTLibAddress.getText();
       
       Library lib = new Library(id, name, loc);
       lib.addLibrary(id, name, loc);
       showLibList();
        
        
       
    }//GEN-LAST:event_jButtonAddLibActionPerformed

    private void jButtonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBookActionPerformed
        // TODO add your handling code here:
        String bookName = jTbookTitle.getText();
        int isbn = Integer.parseInt(jTISBN.getText());
        String bookAuthor = jTBookAuthor.getText();
        String bookLocation = (String)jComboBoxLocation.getSelectedItem();
        double price = Double.parseDouble(jTPrice.getText());
        
        Books book = new Books(bookName, isbn, bookAuthor, bookLocation, price);
        book.addBook(bookName, isbn, bookAuthor, bookLocation, price);
        
        
        
        loadAllBooks();
    }//GEN-LAST:event_jButtonAddBookActionPerformed

    private void jBclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jBclearActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTLibID.setText("");
        jTLibName.setText("");
        jTLibAddress.setText("");
         
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTableLibListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLibListMouseClicked
        // TODO add your handling code here:
            int index = jTableLibList.getSelectedRow();
            TableModel model = jTableLibList.getModel();
            String selected = model.getValueAt(index, 1).toString();
            
            jTLibID.setText(model.getValueAt(index, 0).toString());
            jTLibName.setText(model.getValueAt(index, 1).toString());
            jTLibAddress.setText(model.getValueAt(index, 2).toString());
            
    try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            java.sql.Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/librarysystem","root","1234");  
            //here sonoo is database name, root is username and password
            
            Statement stmt=con.createStatement();  
   
            ResultSet rs = stmt.executeQuery("SELECT libbooks.LIBBOOKNAME, libbooks.LIBBOOKAUTHOR,\n" +
                    "    libbooks.isbn, libbooks.libBookPrice\n" +
                    "    FROM libbooks\n" +
                    "    WHERE libbooks.libBookLocation = '" + selected +"'");
    
            // get columns info
                ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();

            // for changing column and row model
            DefaultTableModel tm;
            tm = (DefaultTableModel) jTableLibBooks.getModel();

            // clear existing columns 
            tm.setColumnCount(0);

            // add specified columns to table
            for (int i = 1; i <= columnCount; i++ ) {
                tm.addColumn(rsmd.getColumnName(i));
            }   

            // clear existing rows
            tm.setRowCount(0);

            // add rows to table
            while (rs.next()) {
                String[] a = new String[columnCount];
                for(int i = 0; i < columnCount; i++) {
                    a[i] = rs.getString(i+1);
                }
            tm.addRow(a);
            }
            tm.fireTableDataChanged();

            // Close ResultSet and Statement
            rs.close();
            stmt.close();

          }catch(Exception e)
          { 
              System.out.println(e);
          }  
    }//GEN-LAST:event_jTableLibListMouseClicked

    private void jTableAvailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAvailMouseClicked
        // TODO add your handling code here:
        int a = jTableAvail.getSelectedRow();
        TableModel model = jTableAvail.getModel();
        
        
        jLabelBookTitle.setText(model.getValueAt(a, 0).toString()) ;
        jLabelLibLoc.setText(model.getValueAt(a, 3).toString()) ;
        jLabelISBN.setText(model.getValueAt(a, 2).toString()) ;
        
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd"); 
        LocalDateTime now = LocalDateTime.now();
        String nowDate = dtf.format(now);
        
        jLabelBorrowDate.setText(nowDate);
        
        
        Calendar calendar = Calendar.getInstance();
        int days = 2;
    // Add days
        calendar.add(Calendar.DAY_OF_MONTH, days);
        
        java.util.Date date = calendar.getTime();
        
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        jLabelReturnDate.setText(simpleDateFormat.format(date).toString());
    }//GEN-LAST:event_jTableAvailMouseClicked

    private void jButtonBorrowBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrowBookActionPerformed
        try {
            // TODO add your handling code here:
           
            int isbn = Integer.parseInt(jLabelISBN.getText());
            String bookBorrower = jTextFieldBorrower.getText();
            String isBorrowed = "yes";
            
            String startDate=jLabelBorrowDate.getText();
            SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date date = sdf1.parse(startDate);
            java.sql.Date borrowDate = new java.sql.Date(date.getTime());
            
            String startDate2=jLabelReturnDate.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date date2 = sdf.parse(startDate2);
            java.sql.Date returnDate = new java.sql.Date(date2.getTime());
            
            
            
            Books newBook = new Books (isbn, bookBorrower, isBorrowed, borrowDate, returnDate);
            newBook.borrowBook(isbn, bookBorrower, isBorrowed, borrowDate, returnDate);
        } catch (ParseException ex) {
            Logger.getLogger(libSystemGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        loadLibBorrowed();
        loadLibAvail();
    }//GEN-LAST:event_jButtonBorrowBookActionPerformed

    private void jButtonReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnBookActionPerformed
        // TODO add your handling code here:
       int a = jTableBorrowed.getSelectedRow();
       TableModel model = jTableBorrowed.getModel();
        
       int selected = Integer.parseInt(model.getValueAt(a, 0).toString());
       Books book = new Books(selected);
       book.returnBook(selected);
       
       loadLibBorrowed();
       loadLibAvail();
        
    }//GEN-LAST:event_jButtonReturnBookActionPerformed

    private void jTableBorrowedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBorrowedMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jTableBorrowedMouseClicked

    private void jTableBookListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBookListMouseClicked
        // TODO add your handling code here:
       int a = jTableBookList.getSelectedRow();
       TableModel model = jTableBookList.getModel();
        
       jLabelUpdateISBN.setText(model.getValueAt(a, 0).toString());
       jTUpdateBookTitle.setText(model.getValueAt(a, 1).toString());
       jTUpdateBookAuthor.setText(model.getValueAt(a, 2).toString());
       jTUpdatePrice.setText(model.getValueAt(a, 3).toString());
       
       
       
    }//GEN-LAST:event_jTableBookListMouseClicked

    private void jButtonUpdateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateBookActionPerformed
        // TODO add your handling code here:
        String bookName = (String)jTUpdateBookTitle.getText();
        int isbn = Integer.parseInt(jLabelUpdateISBN.getText());
        String bookAuthor = (String)jTUpdateBookAuthor.getText();
        String bookLocation = (String)jComboBoxUpdateBook.getSelectedItem();
        double price = Double.parseDouble(jTUpdatePrice.getText());
        
        Books b = new Books(bookName, isbn, bookAuthor, bookLocation, price);
        b.updateBook(bookName, isbn, bookAuthor, bookLocation, price);
        
        loadAllBooks();
        
        
    }//GEN-LAST:event_jButtonUpdateBookActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       int a = jTableLibList.getSelectedRow();
       TableModel model = jTableLibList.getModel();
       
       int id = Integer.parseInt(model.getValueAt(a, 0).toString());
       
        Library newLib = new Library(id);
        newLib.deleteLibrary(id);
        
        showLibList();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonUpdateLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateLibActionPerformed
        // TODO add your handling code here:
        int idlibName = Integer.parseInt(jTLibID.getText());
        String libName = jTLibName.getText();
        String libAddress = jTLibAddress.getText();
              
        Library newLib = new Library(idlibName, libName, libAddress);
        newLib.updateLibrary(idlibName, libName, libAddress);
       
        showLibList();       
    }//GEN-LAST:event_jButtonUpdateLibActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
       System.exit(1);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(libSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(libSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(libSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(libSystemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new libSystemGUI().setVisible(true);
            }
        });
    }
    
    
    public void loadLibrary(){
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/librarysystem","root","1234");
            
            ArrayList<String> groupNames = new ArrayList<String>();
            String query = "SELECT libName FROM libName ORDER BY libName";
            PreparedStatement stm = con.prepareStatement(query);
            
            ResultSet rs = stm.executeQuery(query);
            
            while (rs.next()) {
                String groupName = rs.getString("libName");
                // add group names to the array list
                groupNames.add(groupName);
                        }
            
                rs.close();
            
            
// Populate the combo box
               DefaultComboBoxModel model = new DefaultComboBoxModel(groupNames.toArray());
               jComboBoxBorrowed.setModel(model);
               jComboBoxLocation.setModel(model);
               jComboBoxUpdateBook.setModel(model);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(libSystemGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(libSystemGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
public void showLibList(){
    try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            java.sql.Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/librarysystem","root","1234");  
            //here sonoo is database name, root is username and password
            
            Statement stmt=con.createStatement();  
   
            ResultSet rs = stmt.executeQuery("SELECT * FROM libname");
    
            // get columns info
                ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();

            // for changing column and row model
            DefaultTableModel tm;
            tm = (DefaultTableModel) jTableLibList.getModel();

            // clear existing columns 
            tm.setColumnCount(0);

            // add specified columns to table
            for (int i = 1; i <= columnCount; i++ ) {
                tm.addColumn(rsmd.getColumnName(i));
            }   

            // clear existing rows
            tm.setRowCount(0);

            // add rows to table
            while (rs.next()) {
                String[] a = new String[columnCount];
                for(int i = 0; i < columnCount; i++) {
                    a[i] = rs.getString(i+1);
                }
            tm.addRow(a);
            }
            tm.fireTableDataChanged();

            // Close ResultSet and Statement
            rs.close();
            stmt.close();

          }catch(Exception e)
          { 
              System.out.println(e);
          }  
        
       
        
        
}
public void loadLibAvail(){
    String selected = (String)jComboBoxBorrowed.getSelectedItem();
    try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            java.sql.Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/librarysystem","root","1234");  
            //here sonoo is database name, root is username and password
            
            Statement stmt=con.createStatement();  
   
            ResultSet rs = stmt.executeQuery("SELECT libbooks.LIBBOOKNAME, libbooks.LIBBOOKAUTHOR,\n" +
                    "    libbooks.isbn, libbooks.libBookLocation\n" +
                    "    FROM\n" +
                    "        borrowedbooks RIGHT JOIN libbooks ON borrowedbooks.isbn = libbooks.isbn\n" +
                    "    WHERE borrowedbooks.isBorrowed is NULL AND libbooks.libBookLocation = '" + selected +"'");
    
            // get columns info
                ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();

            // for changing column and row model
            DefaultTableModel tm;
            tm = (DefaultTableModel) jTableAvail.getModel();

            // clear existing columns 
            tm.setColumnCount(0);

            // add specified columns to table
            for (int i = 1; i <= columnCount; i++ ) {
                tm.addColumn(rsmd.getColumnName(i));
            }   

            // clear existing rows
            tm.setRowCount(0);

            // add rows to table
            while (rs.next()) {
                String[] a = new String[columnCount];
                for(int i = 0; i < columnCount; i++) {
                    a[i] = rs.getString(i+1);
                }
            tm.addRow(a);
            }
            tm.fireTableDataChanged();

            // Close ResultSet and Statement
            rs.close();
            stmt.close();

          }catch(Exception e)
          { 
              System.out.println(e);
          }  
}


public void loadLibBorrowed(){
    String selected = (String)jComboBoxBorrowed.getSelectedItem();
    try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            java.sql.Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/librarysystem","root","1234");  
            //here sonoo is database name, root is username and password
            
            Statement stmt=con.createStatement();  
   
            ResultSet rs = stmt.executeQuery("SELECT libbooks.ISBN, libbooks.LIBBOOKNAME, libbooks.LIBBOOKAUTHOR,\n" +
                    "    borrowedBooks.borrowerBook, borrowedBooks.returnDate\n" +
                    "    FROM\n" +
                    "        borrowedBooks JOIN libbooks ON borrowedBooks.isbn = libbooks.isbn\n" +
                    "    WHERE borrowedBooks.isBorrowed = 'yes' AND libbooks.libBookLocation = '" + selected +"'");
    
            // get columns info
                ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();

            // for changing column and row model
            DefaultTableModel tm;
            tm = (DefaultTableModel) jTableBorrowed.getModel();

            // clear existing columns 
            tm.setColumnCount(0);

            // add specified columns to table
            for (int i = 1; i <= columnCount; i++ ) {
                tm.addColumn(rsmd.getColumnName(i));
            }   

            // clear existing rows
            tm.setRowCount(0);

            // add rows to table
            while (rs.next()) {
                String[] a = new String[columnCount];
                for(int i = 0; i < columnCount; i++) {
                    a[i] = rs.getString(i+1);
                }
            tm.addRow(a);
            }
            tm.fireTableDataChanged();

            // Close ResultSet and Statement
            rs.close();
            stmt.close();

          }catch(Exception e)
          { 
              System.out.println(e);
          }  
}
public void clear(){
    jTbookTitle.setText("");
    jTISBN.setText("");
    jTBookAuthor.setText("");
    jTPrice.setText("");
}
public void loadAllBooks(){
    try{  
            Class.forName("com.mysql.cj.jdbc.Driver");  
            java.sql.Connection con=DriverManager.getConnection(  
            "jdbc:mysql://localhost:3306/librarysystem","root","1234");  
            //here sonoo is database name, root is username and password
            
            Statement stmt=con.createStatement();  
   
            ResultSet rs = stmt.executeQuery("SELECT * from libbooks;");
    
            // get columns info
                ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();

            // for changing column and row model
            DefaultTableModel tm;
            tm = (DefaultTableModel) jTableBookList.getModel();

            // clear existing columns 
            tm.setColumnCount(0);

            // add specified columns to table
            for (int i = 1; i <= columnCount; i++ ) {
                tm.addColumn(rsmd.getColumnName(i));
            }   

            // clear existing rows
            tm.setRowCount(0);

            // add rows to table
            while (rs.next()) {
                String[] a = new String[columnCount];
                for(int i = 0; i < columnCount; i++) {
                    a[i] = rs.getString(i+1);
                }
            tm.addRow(a);
            }
            tm.fireTableDataChanged();

            // Close ResultSet and Statement
            rs.close();
            stmt.close();

          }catch(Exception e)
          { 
              System.out.println(e);
          }  
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBclear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAddBook;
    private javax.swing.JButton jButtonAddLib;
    private javax.swing.JButton jButtonBorrowBook;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonReturnBook;
    private javax.swing.JButton jButtonUpdateBook;
    private javax.swing.JButton jButtonUpdateLib;
    private javax.swing.JComboBox<String> jComboBoxBorrowed;
    private javax.swing.JComboBox<String> jComboBoxLocation;
    private javax.swing.JComboBox<String> jComboBoxUpdateBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBookTitle;
    private javax.swing.JLabel jLabelBorrowDate;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelLibLoc;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelR;
    private javax.swing.JLabel jLabelReturnDate;
    private javax.swing.JLabel jLabelUpdateISBN;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBooks;
    private javax.swing.JPanel jPannelAddLib;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTBookAuthor;
    private javax.swing.JTextField jTISBN;
    private javax.swing.JTextField jTLibAddress;
    private javax.swing.JTextField jTLibID;
    private javax.swing.JTextField jTLibName;
    private javax.swing.JTextField jTPrice;
    private javax.swing.JTextField jTUpdateBookAuthor;
    private javax.swing.JTextField jTUpdateBookTitle;
    private javax.swing.JTextField jTUpdatePrice;
    private javax.swing.JTabbedPane jTabbedPaneLib;
    private javax.swing.JTable jTableAvail;
    private javax.swing.JTable jTableBookList;
    private javax.swing.JTable jTableBorrowed;
    private javax.swing.JTable jTableLibBooks;
    private javax.swing.JTable jTableLibList;
    private javax.swing.JTextField jTbookTitle;
    private javax.swing.JTextField jTextFieldBorrower;
    // End of variables declaration//GEN-END:variables
}
